/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedAiInsightsRouteImport } from './routes/_authenticated/ai-insights'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as ApiPublicTriggerMockTestRouteImport } from './routes/api/public/trigger-mock-test'
import { Route as ApiPublicTriggerImportSeoRouteImport } from './routes/api/public/trigger-import-seo'
import { Route as ApiPublicTriggerImportRdMarketingRouteImport } from './routes/api/public/trigger-import-rd-marketing'
import { Route as ApiPublicTriggerImportMetaRouteImport } from './routes/api/public/trigger-import-meta'
import { Route as ApiPublicTriggerImportGoogleAdsRouteImport } from './routes/api/public/trigger-import-google-ads'
import { Route as ApiPublicTriggerImportRouteImport } from './routes/api/public/trigger-import'
import { Route as ApiPublicSheetsAuditRouteImport } from './routes/api/public/sheets-audit'
import { Route as ApiPublicRdIngestRouteImport } from './routes/api/public/rd-ingest'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicGscIngestRouteImport } from './routes/api/public/gsc-ingest'
import { Route as ApiPublicAdsIngestRouteImport } from './routes/api/public/ads-ingest'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiInsightsRoute = AuthenticatedAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicTriggerMockTestRoute =
  ApiPublicTriggerMockTestRouteImport.update({
    id: '/api/public/trigger-mock-test',
    path: '/api/public/trigger-mock-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTriggerImportSeoRoute =
  ApiPublicTriggerImportSeoRouteImport.update({
    id: '/api/public/trigger-import-seo',
    path: '/api/public/trigger-import-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTriggerImportRdMarketingRoute =
  ApiPublicTriggerImportRdMarketingRouteImport.update({
    id: '/api/public/trigger-import-rd-marketing',
    path: '/api/public/trigger-import-rd-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTriggerImportMetaRoute =
  ApiPublicTriggerImportMetaRouteImport.update({
    id: '/api/public/trigger-import-meta',
    path: '/api/public/trigger-import-meta',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTriggerImportGoogleAdsRoute =
  ApiPublicTriggerImportGoogleAdsRouteImport.update({
    id: '/api/public/trigger-import-google-ads',
    path: '/api/public/trigger-import-google-ads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTriggerImportRoute = ApiPublicTriggerImportRouteImport.update({
  id: '/api/public/trigger-import',
  path: '/api/public/trigger-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSheetsAuditRoute = ApiPublicSheetsAuditRouteImport.update({
  id: '/api/public/sheets-audit',
  path: '/api/public/sheets-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRdIngestRoute = ApiPublicRdIngestRouteImport.update({
  id: '/api/public/rd-ingest',
  path: '/api/public/rd-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGscIngestRoute = ApiPublicGscIngestRouteImport.update({
  id: '/api/public/gsc-ingest',
  path: '/api/public/gsc-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdsIngestRoute = ApiPublicAdsIngestRouteImport.update({
  id: '/api/public/ads-ingest',
  path: '/api/public/ads-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/api/public/ads-ingest': typeof ApiPublicAdsIngestRoute
  '/api/public/gsc-ingest': typeof ApiPublicGscIngestRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/rd-ingest': typeof ApiPublicRdIngestRoute
  '/api/public/sheets-audit': typeof ApiPublicSheetsAuditRoute
  '/api/public/trigger-import': typeof ApiPublicTriggerImportRoute
  '/api/public/trigger-import-google-ads': typeof ApiPublicTriggerImportGoogleAdsRoute
  '/api/public/trigger-import-meta': typeof ApiPublicTriggerImportMetaRoute
  '/api/public/trigger-import-rd-marketing': typeof ApiPublicTriggerImportRdMarketingRoute
  '/api/public/trigger-import-seo': typeof ApiPublicTriggerImportSeoRoute
  '/api/public/trigger-mock-test': typeof ApiPublicTriggerMockTestRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/api/public/ads-ingest': typeof ApiPublicAdsIngestRoute
  '/api/public/gsc-ingest': typeof ApiPublicGscIngestRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/rd-ingest': typeof ApiPublicRdIngestRoute
  '/api/public/sheets-audit': typeof ApiPublicSheetsAuditRoute
  '/api/public/trigger-import': typeof ApiPublicTriggerImportRoute
  '/api/public/trigger-import-google-ads': typeof ApiPublicTriggerImportGoogleAdsRoute
  '/api/public/trigger-import-meta': typeof ApiPublicTriggerImportMetaRoute
  '/api/public/trigger-import-rd-marketing': typeof ApiPublicTriggerImportRdMarketingRoute
  '/api/public/trigger-import-seo': typeof ApiPublicTriggerImportSeoRoute
  '/api/public/trigger-mock-test': typeof ApiPublicTriggerMockTestRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/api/public/ads-ingest': typeof ApiPublicAdsIngestRoute
  '/api/public/gsc-ingest': typeof ApiPublicGscIngestRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/rd-ingest': typeof ApiPublicRdIngestRoute
  '/api/public/sheets-audit': typeof ApiPublicSheetsAuditRoute
  '/api/public/trigger-import': typeof ApiPublicTriggerImportRoute
  '/api/public/trigger-import-google-ads': typeof ApiPublicTriggerImportGoogleAdsRoute
  '/api/public/trigger-import-meta': typeof ApiPublicTriggerImportMetaRoute
  '/api/public/trigger-import-rd-marketing': typeof ApiPublicTriggerImportRdMarketingRoute
  '/api/public/trigger-import-seo': typeof ApiPublicTriggerImportSeoRoute
  '/api/public/trigger-mock-test': typeof ApiPublicTriggerMockTestRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-insights'
    | '/automations'
    | '/costs'
    | '/dashboard'
    | '/integrations'
    | '/reports'
    | '/roadmap'
    | '/settings'
    | '/templates'
    | '/users'
    | '/clients/$id'
    | '/api/public/ads-ingest'
    | '/api/public/gsc-ingest'
    | '/api/public/ingest'
    | '/api/public/rd-ingest'
    | '/api/public/sheets-audit'
    | '/api/public/trigger-import'
    | '/api/public/trigger-import-google-ads'
    | '/api/public/trigger-import-meta'
    | '/api/public/trigger-import-rd-marketing'
    | '/api/public/trigger-import-seo'
    | '/api/public/trigger-mock-test'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-insights'
    | '/automations'
    | '/costs'
    | '/dashboard'
    | '/integrations'
    | '/reports'
    | '/roadmap'
    | '/settings'
    | '/templates'
    | '/users'
    | '/clients/$id'
    | '/api/public/ads-ingest'
    | '/api/public/gsc-ingest'
    | '/api/public/ingest'
    | '/api/public/rd-ingest'
    | '/api/public/sheets-audit'
    | '/api/public/trigger-import'
    | '/api/public/trigger-import-google-ads'
    | '/api/public/trigger-import-meta'
    | '/api/public/trigger-import-rd-marketing'
    | '/api/public/trigger-import-seo'
    | '/api/public/trigger-mock-test'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-insights'
    | '/_authenticated/automations'
    | '/_authenticated/costs'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/reports'
    | '/_authenticated/roadmap'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/users'
    | '/_authenticated/clients/$id'
    | '/api/public/ads-ingest'
    | '/api/public/gsc-ingest'
    | '/api/public/ingest'
    | '/api/public/rd-ingest'
    | '/api/public/sheets-audit'
    | '/api/public/trigger-import'
    | '/api/public/trigger-import-google-ads'
    | '/api/public/trigger-import-meta'
    | '/api/public/trigger-import-rd-marketing'
    | '/api/public/trigger-import-seo'
    | '/api/public/trigger-mock-test'
    | '/_authenticated/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAdsIngestRoute: typeof ApiPublicAdsIngestRoute
  ApiPublicGscIngestRoute: typeof ApiPublicGscIngestRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicRdIngestRoute: typeof ApiPublicRdIngestRoute
  ApiPublicSheetsAuditRoute: typeof ApiPublicSheetsAuditRoute
  ApiPublicTriggerImportRoute: typeof ApiPublicTriggerImportRoute
  ApiPublicTriggerImportGoogleAdsRoute: typeof ApiPublicTriggerImportGoogleAdsRoute
  ApiPublicTriggerImportMetaRoute: typeof ApiPublicTriggerImportMetaRoute
  ApiPublicTriggerImportRdMarketingRoute: typeof ApiPublicTriggerImportRdMarketingRoute
  ApiPublicTriggerImportSeoRoute: typeof ApiPublicTriggerImportSeoRoute
  ApiPublicTriggerMockTestRoute: typeof ApiPublicTriggerMockTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-insights': {
      id: '/_authenticated/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AuthenticatedAiInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/trigger-mock-test': {
      id: '/api/public/trigger-mock-test'
      path: '/api/public/trigger-mock-test'
      fullPath: '/api/public/trigger-mock-test'
      preLoaderRoute: typeof ApiPublicTriggerMockTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trigger-import-seo': {
      id: '/api/public/trigger-import-seo'
      path: '/api/public/trigger-import-seo'
      fullPath: '/api/public/trigger-import-seo'
      preLoaderRoute: typeof ApiPublicTriggerImportSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trigger-import-rd-marketing': {
      id: '/api/public/trigger-import-rd-marketing'
      path: '/api/public/trigger-import-rd-marketing'
      fullPath: '/api/public/trigger-import-rd-marketing'
      preLoaderRoute: typeof ApiPublicTriggerImportRdMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trigger-import-meta': {
      id: '/api/public/trigger-import-meta'
      path: '/api/public/trigger-import-meta'
      fullPath: '/api/public/trigger-import-meta'
      preLoaderRoute: typeof ApiPublicTriggerImportMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trigger-import-google-ads': {
      id: '/api/public/trigger-import-google-ads'
      path: '/api/public/trigger-import-google-ads'
      fullPath: '/api/public/trigger-import-google-ads'
      preLoaderRoute: typeof ApiPublicTriggerImportGoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trigger-import': {
      id: '/api/public/trigger-import'
      path: '/api/public/trigger-import'
      fullPath: '/api/public/trigger-import'
      preLoaderRoute: typeof ApiPublicTriggerImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sheets-audit': {
      id: '/api/public/sheets-audit'
      path: '/api/public/sheets-audit'
      fullPath: '/api/public/sheets-audit'
      preLoaderRoute: typeof ApiPublicSheetsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rd-ingest': {
      id: '/api/public/rd-ingest'
      path: '/api/public/rd-ingest'
      fullPath: '/api/public/rd-ingest'
      preLoaderRoute: typeof ApiPublicRdIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gsc-ingest': {
      id: '/api/public/gsc-ingest'
      path: '/api/public/gsc-ingest'
      fullPath: '/api/public/gsc-ingest'
      preLoaderRoute: typeof ApiPublicGscIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ads-ingest': {
      id: '/api/public/ads-ingest'
      path: '/api/public/ads-ingest'
      fullPath: '/api/public/ads-ingest'
      preLoaderRoute: typeof ApiPublicAdsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiInsightsRoute: typeof AuthenticatedAiInsightsRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiInsightsRoute: AuthenticatedAiInsightsRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAdsIngestRoute: ApiPublicAdsIngestRoute,
  ApiPublicGscIngestRoute: ApiPublicGscIngestRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicRdIngestRoute: ApiPublicRdIngestRoute,
  ApiPublicSheetsAuditRoute: ApiPublicSheetsAuditRoute,
  ApiPublicTriggerImportRoute: ApiPublicTriggerImportRoute,
  ApiPublicTriggerImportGoogleAdsRoute: ApiPublicTriggerImportGoogleAdsRoute,
  ApiPublicTriggerImportMetaRoute: ApiPublicTriggerImportMetaRoute,
  ApiPublicTriggerImportRdMarketingRoute:
    ApiPublicTriggerImportRdMarketingRoute,
  ApiPublicTriggerImportSeoRoute: ApiPublicTriggerImportSeoRoute,
  ApiPublicTriggerMockTestRoute: ApiPublicTriggerMockTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
